# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class NbaScrapingProjectItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass

class TotalsPlayerItem(scrapy.Item): 
    ranking = scrapy.Field()
    name = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    team = scrapy.Field()
    games_played = scrapy.Field()
    games_started = scrapy.Field()
    minutes_played = scrapy.Field()
    field_goal_made = scrapy.Field()
    field_goal_attempts = scrapy.Field()
    field_goal_percentage = scrapy.Field()
    three_pts_made = scrapy.Field()
    three_pts_attempts = scrapy.Field()
    three_pt_percentage = scrapy.Field()
    two_pts_made = scrapy.Field()
    two_pts_attempts = scrapy.Field()
    two_pts_percentage = scrapy.Field()
    effective_field_goal_percentage = scrapy.Field()
    free_throw_made = scrapy.Field()
    free_throw_attempts = scrapy.Field()
    free_throw_percentage = scrapy.Field()
    offensive_rebound = scrapy.Field()
    defensive_rebound = scrapy.Field()
    total_rebound = scrapy.Field()
    assists = scrapy.Field()
    turnover = scrapy.Field()
    steals = scrapy.Field()
    blocks = scrapy.Field()
    personal_fouls = scrapy.Field()
    points = scrapy.Field()
    
    

class PlayerPerGameItem(scrapy.Item):
    ranking = scrapy.Field()
    name = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    team = scrapy.Field()
    games_played = scrapy.Field()
    games_started = scrapy.Field()
    minutes_played_pg = scrapy.Field()
    field_goal_made_pg = scrapy.Field()
    field_goal_attempts_pg = scrapy.Field()
    field_goal_percentage = scrapy.Field()
    three_pts_made_pg = scrapy.Field()
    three_pts_attempts_pg = scrapy.Field()
    three_pt_percentage = scrapy.Field()
    two_pts_made_pg = scrapy.Field()
    two_pts_attempts_pg = scrapy.Field()
    two_pts_percentage = scrapy.Field()
    effective_field_goal_percentage = scrapy.Field()
    free_throw_made_pg = scrapy.Field()
    free_throw_attempts_pg = scrapy.Field()
    free_throw_percentage = scrapy.Field()
    offensive_rebound_pg = scrapy.Field()
    defensive_rebound_pg = scrapy.Field()
    total_rebound_pg = scrapy.Field()
    assists_pg = scrapy.Field()
    turnover_pg = scrapy.Field()
    steals_pg = scrapy.Field()
    blocks_pg = scrapy.Field()
    personal_fouls_pg = scrapy.Field()
    points_pg = scrapy.Field()
    

class PlayerPer36MinItem(scrapy.Item): 
    ranking = scrapy.Field()
    name = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    team = scrapy.Field()
    games_played = scrapy.Field()
    games_started = scrapy.Field()
    minutes_played = scrapy.Field()
    field_goal_made_36 = scrapy.Field()
    field_goal_attempts_36 = scrapy.Field()
    field_goal_percentage = scrapy.Field()
    three_pts_made_36 = scrapy.Field()
    three_pts_attempts_36 = scrapy.Field()
    three_pt_percentage = scrapy.Field()
    two_pts_made_36 = scrapy.Field()
    two_pts_attempts_36 = scrapy.Field()
    two_pts_percentage = scrapy.Field()
    free_throw_made_36 = scrapy.Field()
    free_throw_attempts_36 = scrapy.Field()
    free_throw_percentage = scrapy.Field()
    offensive_rebound_36 = scrapy.Field()
    defensive_rebound_36 = scrapy.Field()
    total_rebound_36 = scrapy.Field()
    assists_36 = scrapy.Field()
    turnover_36 = scrapy.Field()
    steals_36 = scrapy.Field()
    blocks_36 = scrapy.Field()
    personal_fouls_36 = scrapy.Field()
    points_36 = scrapy.Field()
    
    
class PlayerPer100TeamPossession(scrapy.Item):
    ranking = scrapy.Field()
    name = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    team = scrapy.Field()
    games_played = scrapy.Field()
    games_started = scrapy.Field()
    minutes_played = scrapy.Field()
    field_goals_per_100 = scrapy.Field() 
    field_goal_attempts_per_100 = scrapy.Field()
    field_goal_percentage = scrapy.Field()
    three_pts_made_per_100 = scrapy.Field()
    three_pts_attempts_per_100 = scrapy.Field()
    three_pt_percentage = scrapy.Field()
    two_pts_made_per_100 = scrapy.Field()
    two_pts_attempts_per_100 = scrapy.Field()
    two_pts_percentage = scrapy.Field()
    free_throw_made_per_100 = scrapy.Field()
    free_throw_attempts_per_100 = scrapy.Field()
    free_throw_percentage = scrapy.Field()
    offensive_rebound_per_100 = scrapy.Field()
    defensive_rebound_per_100 = scrapy.Field()
    total_rebound_per_100 = scrapy.Field()
    assists_per_100 = scrapy.Field()
    steals_per_100 = scrapy.Field()
    blocks_per_100 = scrapy.Field()
    turnover_per_100 = scrapy.Field()
    personal_fouls_per_100 = scrapy.Field()
    points_per_100 = scrapy.Field()
    offensive_rating = scrapy.Field()
    defensive_rating = scrapy.Field()


class AdvancedPlayerStats(scrapy.Item): 
    ranking = scrapy.Field()
    name = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    team = scrapy.Field()
    games_played = scrapy.Field()
    minutes_played = scrapy.Field()
    player_efficiency_rating = scrapy.Field()
    true_shooting_percentage = scrapy.Field()
    three_pts_attempt_rate = scrapy.Field()
    free_throw_attempt_rate = scrapy.Field()
    offensive_rebound_percentage = scrapy.Field()
    defensive_rebound_percentage = scrapy.Field()
    total_rebound_percentage = scrapy.Field()
    assists_percentage = scrapy.Field()
    steal_percentage = scrapy.Field()
    block_percentage = scrapy.Field()
    turnover_percentage = scrapy.Field()
    usage_percentage = scrapy.Field()
    offensive_win_shares = scrapy.Field()
    defensive_win_shares = scrapy.Field()
    win_shares = scrapy.Field()
    win_shares_per_48 = scrapy.Field() 
    offensive_box_plus_minus = scrapy.Field()
    defensive_box_plus_minus = scrapy.Field()
    box_plus_minus = scrapy.Field()
    value_over_replacement_player = scrapy.Field()

    
class PlayerShooting(scrapy.Item): 
    ranking = scrapy.Field()
    name = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    team = scrapy.Field()
    games_played = scrapy.Field()
    minutes_played = scrapy.Field()
    field_goal_percentage = scrapy.Field()
    average_distance_field_goal = scrapy.Field()
    percentage_field_goal_attempts_2pts = scrapy.Field()
    percentage_field_goal_attempts_0to3ft = scrapy.Field()
    percentage_field_goal_attempts_3to10ft = scrapy.Field()
    percentage_field_goal_attempts_10to16ft = scrapy.Field()
    percentage_field_goal_attempts_16to3pts = scrapy.Field()
    percentage_field_goal_attempts_3pts = scrapy.Field()
    percentage_fg_made_2pts = scrapy.Field()
    percentage_fg_made_0to3ft = scrapy.Field()
    percentage_fg_made_3to10ft = scrapy.Field()
    percentage_fg_made_10to16ft = scrapy.Field()
    percentage_fg_made_16to3pts = scrapy.Field()
    percentage_fg_made_3pts = scrapy.Field()
    percentage_fg_assists_2pts= scrapy.Field()
    percentage_fg_assists_3pts = scrapy.Field()
    percentage_dunks_over_total_fg_attempts = scrapy.Field()
    number_of_dunks = scrapy.Field()
    percentage_corner3pts_over_total_3pts_fg_attempts = scrapy.Field()
    percentage_corner3pts_made = scrapy.Field()
    
    
class PlayerAdjustedShooting(scrapy.Item): 
    ranking = scrapy.Field()
    name = scrapy.Field()
    position = scrapy.Field()
    age = scrapy.Field()
    team = scrapy.Field()
    games_played = scrapy.Field()
    minutes_played = scrapy.Field()
    overall_field_goal_percentage = scrapy.Field()
    two_pts_field_goal_percentage = scrapy.Field()
    three_pts_field_goal_percentage = scrapy.Field()
    effective_field_goal_percentage = scrapy.Field()
    free_throw_percentage = scrapy.Field()
    true_shooting_percentage = scrapy.Field()
    free_throw_per_field_goal_percentage = scrapy.Field()
    league_adjusted_overall_field_goal_percentage = scrapy.Field()
    league_adjusted_2pts_field_goal_percentage = scrapy.Field()
    league_adjusted_3pts_field_goal_percentage = scrapy.Field()
    league_adjusted_effective_field_goal_percentage = scrapy.Field()
    league_adjusted_free_throw_percentage = scrapy.Field()
    league_adjusted_true_shooting_percentage = scrapy.Field()
    league_adjusted_free_throw_per_field_goal_percentage = scrapy.Field()
    extra_pts_by_FGA_above_league_average = scrapy.Field()
    extra_pts_by_TrueShotAttempts_above_league_average = scrapy.Field()
    
    
    
